# Generated by Django 3.0 on 2020-08-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsent',
            name='contact',
        ),
        migrations.AddField(
            model_name='emailsent',
            name='contact',
            field=models.ManyToManyField(to='marketing.Contact'),
        ),
    ]
