# Generated by Django 3.0 on 2020-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200814_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True)),
                ('subject', models.TextField()),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailsent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='emailsent',
            name='sender',
        ),
        migrations.AddField(
            model_name='emailsent',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='from_address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailsent',
            name='subject',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EmailContent',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
