# Generated by Django 3.0 on 2020-08-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20200814_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
